
/**************************************************************
 *    
 *    korobeiniki, 8 bit, 22050Hz,
 *    1 channel, 850777 bytes/channel
 *    Total Size: 1 * 850777 + 4 (header) = 851069 bytes
 *    
 *    Generated by wav2c v1.0 from:
 *    korobeiniki.wav
 *    Time-stamp: Thu Mar 31 19:39:06 2016
 *    
 **************************************************************/

#ifndef __KOROBEINIKIH__
#define __KOROBEINIKIH__

#define KOROBEINIKIFREQ 22050
#define KOROBEINIKILEN 849000

extern const unsigned char korobeiniki[850777];

#endif /* __KOROBEINIKIH__ */
